//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transportworld
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int VehicleID { get; set; }
        public int DriverID { get; set; }
        public string VehicleType { get; set; }
        public string RegistrationNumber { get; set; }
        public string Route { get; set; }
    
        public virtual Driver Driver { get; set; }
    }
}
